import { TripPlan } from './types';

export const yellowstoneSeed: TripPlan = {
  title: '4-Day Luxury Family Yellowstone Getaway',
  dates: 'Jul 1 – Jul 5, 2026',
  durationDays: 4,
  cities: 3,
  activities: 11,
  transportLegs: 2,
  travelers: 3,
  currency: 'EUR',
  days: [
    { day: 1, date: '2026-07-01', title: 'Arrival & Mammoth' },
    { day: 2, date: '2026-07-02', title: 'Geyser Circuit' },
    { day: 3, date: '2026-07-03', title: 'Canyon & Wildlife' },
    { day: 4, date: '2026-07-04', title: 'Norris & Photography' }
  ],
  nodes: [
    {
      id: 'flight-in',
      title: 'United Flight Richmond → Bozeman',
      category: 'flight',
      day: 1,
      timeWindow: '06:20–14:04',
      duration: '7h 44m',
      location: 'RIC → BZN',
      cost: 2520,
      priority: 'high',
      reservationStatus: 'booked',
      notes: '1 stop · family seats together',
      tags: ['arrival', 'air'],
      icon: '✈️'
    },
    {
      id: 'private-transfer',
      title: 'Private Transfer to Yellowstone',
      category: 'transport',
      day: 1,
      timeWindow: '14:30–16:00',
      duration: '1h 30m',
      location: 'Bozeman Airport → Yellowstone',
      cost: 438,
      priority: 'medium',
      reservationStatus: 'booked',
      notes: 'Luxury SUV with child seat',
      tags: ['ground transport'],
      icon: '🚘'
    },
    {
      id: 'mammoth',
      title: 'Mammoth',
      category: 'attraction',
      day: 1,
      timeWindow: '17:00–18:30',
      duration: '1h 30m',
      location: 'Mammoth Hot Springs',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Light walk on arrival day',
      tags: ['nature', 'family'],
      icon: '🏞️'
    },
    {
      id: 'mammoth-dining',
      title: 'Mammoth Dining Room',
      category: 'restaurant',
      day: 1,
      timeWindow: '19:00–20:30',
      duration: '1h 30m',
      location: 'Mammoth Hotel',
      cost: 190,
      priority: 'high',
      reservationStatus: 'pending',
      notes: 'Window-side table requested',
      tags: ['dinner'],
      icon: '🍽️'
    },
    {
      id: 'old-faithful',
      title: 'Old Faithful Geyser',
      category: 'attraction',
      day: 2,
      timeWindow: '08:00–09:00',
      duration: '1h',
      location: 'Old Faithful Area',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Catch morning eruption window',
      tags: ['must-see'],
      icon: '🌋'
    },
    {
      id: 'grand-prismatic',
      title: 'Grand Prismatic Spring',
      category: 'scenic_point',
      day: 2,
      timeWindow: '09:30–11:00',
      duration: '1h 30m',
      location: 'Midway Geyser Basin',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Drone banned. Bring wide lens.',
      tags: ['photography'],
      icon: '🌈'
    },
    {
      id: 'castle-geyser',
      title: 'Castle Geyser',
      category: 'attraction',
      day: 2,
      timeWindow: '11:30–12:15',
      duration: '45m',
      location: 'Upper Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Flexible timing by eruption prediction',
      tags: ['geyser'],
      icon: '🗻'
    },
    {
      id: 'fountain-paint-pot',
      title: 'Fountain Paint Pot',
      category: 'attraction',
      day: 2,
      timeWindow: '13:30–14:30',
      duration: '1h',
      location: 'Lower Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Boardwalk route stroller friendly',
      tags: ['family'],
      icon: '🎨'
    },
    {
      id: 'west-thumb',
      title: 'West Thumb Geyser Basin',
      category: 'scenic_point',
      day: 2,
      timeWindow: '15:30–17:00',
      duration: '1h 30m',
      location: 'Yellowstone Lake',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Golden hour by the lake',
      tags: ['lake view'],
      icon: '🌊'
    },
    {
      id: 'weather-decision',
      title: 'Weather Decision Gate',
      category: 'decision',
      day: 2,
      timeWindow: '17:00–17:15',
      duration: '15m',
      location: 'West Thumb parking',
      cost: 0,
      priority: 'low',
      reservationStatus: 'not_required',
      notes: 'If storms roll in, switch to fallback plan',
      tags: ['branching'],
      icon: '🔀'
    },
    {
      id: 'indoor-fallback',
      title: 'Visitor Center + Relaxed Dinner',
      category: 'fallback',
      day: 2,
      timeWindow: '17:30–20:00',
      duration: '2h 30m',
      location: 'Old Faithful Visitor Education Center',
      cost: 120,
      priority: 'low',
      reservationStatus: 'not_required',
      notes: 'Backup for thunderstorms',
      tags: ['optional', 'weather-safe'],
      icon: '☔',
      optional: true
    },
    {
      id: 'grand-canyon',
      title: 'Grand Canyon of Yellowstone',
      category: 'scenic_point',
      day: 3,
      timeWindow: '08:30–10:00',
      duration: '1h 30m',
      location: 'South Rim Drive',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Artist Point first',
      tags: ['iconic'],
      icon: '🏜️'
    },
    {
      id: 'upper-falls',
      title: 'Yellowstone Upper Falls',
      category: 'scenic_point',
      day: 3,
      timeWindow: '10:15–11:00',
      duration: '45m',
      location: 'Brink of Upper Falls',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Short but steep walk',
      tags: ['waterfall'],
      icon: '💧'
    },
    {
      id: 'hayden',
      title: 'Hayden Valley',
      category: 'scenic_point',
      day: 3,
      timeWindow: '14:00–15:30',
      duration: '1h 30m',
      location: 'Hayden Valley viewpoints',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Best for bison spotting',
      tags: ['wildlife'],
      icon: '🦬'
    },
    {
      id: 'wildlife-safari',
      title: 'Sunset Wildlife Safari',
      category: 'guided_activity',
      day: 3,
      timeWindow: '18:00–21:00',
      duration: '3h',
      location: 'Northern Range',
      cost: 560,
      priority: 'high',
      reservationStatus: 'pending',
      notes: 'Naturalist guide included',
      tags: ['guided', 'sunset'],
      icon: '🧭'
    },
    {
      id: 'norris',
      title: 'Norris Geyser Basin',
      category: 'attraction',
      day: 4,
      timeWindow: '08:30–10:00',
      duration: '1h 30m',
      location: 'Norris',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Cooler morning recommended',
      tags: ['geyser basin'],
      icon: '♨️'
    },
    {
      id: 'black-sand',
      title: 'Black Sand Basin',
      category: 'scenic_point',
      day: 4,
      timeWindow: '10:45–11:45',
      duration: '1h',
      location: 'Upper Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Short colorful loop',
      tags: ['thermal'],
      icon: '🖤'
    },
    {
      id: 'lake-butte',
      title: 'Lake Butte Overlook',
      category: 'scenic_point',
      day: 4,
      timeWindow: '13:00–14:00',
      duration: '1h',
      location: 'East of Yellowstone Lake',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Best with clear skies',
      tags: ['overlook'],
      icon: '📸'
    },
    {
      id: 'photo-tour',
      title: 'Photography Tour',
      category: 'guided_activity',
      day: 4,
      timeWindow: '15:00–17:30',
      duration: '2h 30m',
      location: 'Yellowstone Lake area',
      cost: 480,
      priority: 'medium',
      reservationStatus: 'booked',
      notes: 'Private guide + premium lenses',
      tags: ['guided', 'photo'],
      icon: '📷'
    },
    {
      id: 'slippery-otter',
      title: 'Slippery Otter Pub',
      category: 'restaurant',
      day: 4,
      timeWindow: '19:00–20:30',
      duration: '1h 30m',
      location: 'West Yellowstone',
      cost: 170,
      priority: 'high',
      reservationStatus: 'required',
      notes: 'Reserve patio if weather permits',
      tags: ['dinner', 'local favorite'],
      icon: '🍺'
    },
    {
      id: 'flight-out',
      title: 'Bozeman → Richmond Return Flight',
      category: 'flight',
      day: 4,
      timeWindow: '21:45–04:24+1',
      duration: '6h 39m',
      location: 'BZN → RIC',
      cost: 0,
      priority: 'high',
      reservationStatus: 'booked',
      notes: 'Red-eye return',
      tags: ['return'],
      icon: '🛫'
    }
  ],
  edges: [
    { id: 'e1', source: 'flight-in', target: 'private-transfer', critical: true },
    { id: 'e2', source: 'private-transfer', target: 'mammoth', critical: true },
    { id: 'e3', source: 'mammoth', target: 'mammoth-dining', critical: true },
    { id: 'e4', source: 'mammoth-dining', target: 'old-faithful', critical: true },
    { id: 'e5', source: 'old-faithful', target: 'grand-prismatic', critical: true },
    { id: 'e6', source: 'grand-prismatic', target: 'castle-geyser', critical: true },
    { id: 'e7', source: 'castle-geyser', target: 'fountain-paint-pot', critical: true },
    { id: 'e8', source: 'fountain-paint-pot', target: 'west-thumb', critical: true },
    { id: 'e9', source: 'west-thumb', target: 'weather-decision', critical: true },
    { id: 'e10', source: 'weather-decision', target: 'grand-canyon', label: 'clear skies', critical: true },
    { id: 'e11', source: 'weather-decision', target: 'indoor-fallback', label: 'storm route' },
    { id: 'e12', source: 'indoor-fallback', target: 'grand-canyon', label: 'next morning' },
    { id: 'e13', source: 'grand-canyon', target: 'upper-falls', critical: true },
    { id: 'e14', source: 'upper-falls', target: 'hayden', critical: true },
    { id: 'e15', source: 'hayden', target: 'wildlife-safari', critical: true },
    { id: 'e16', source: 'wildlife-safari', target: 'norris', critical: true },
    { id: 'e17', source: 'norris', target: 'black-sand', critical: true },
    { id: 'e18', source: 'black-sand', target: 'lake-butte', critical: true },
    { id: 'e19', source: 'lake-butte', target: 'photo-tour', critical: true },
    { id: 'e20', source: 'photo-tour', target: 'slippery-otter', critical: true },
    { id: 'e21', source: 'slippery-otter', target: 'flight-out', critical: true }
  ]
};
