import { TripNodeData, TripPlan, TripNodeType } from './types';

type SeedNode = Omit<TripNodeData, 'weights' | 'geo'> & {
  geo: { lat: number; lng: number };
  weights?: Partial<TripNodeData['weights']>;
};

const defaultWeights = {
  joy: 7,
  timeCost: 5,
  budgetImpact: 4,
  effort: 4,
  uniqueness: 6
};

function node(seed: SeedNode): TripNodeData {
  return {
    ...seed,
    weights: {
      ...defaultWeights,
      ...seed.weights
    }
  };
}

const create = (data: SeedNode[]) => data.map((d) => node(d));

export const yellowstoneSeed: TripPlan = {
  title: '4-Day Luxury Family Yellowstone Getaway',
  dates: 'Jul 1 – Jul 5, 2026',
  durationDays: 4,
  cities: 3,
  activities: 11,
  transportLegs: 2,
  travelers: 3,
  currency: 'EUR',
  days: [
    { day: 1, date: '2026-07-01', title: 'Arrival & Mammoth' },
    { day: 2, date: '2026-07-02', title: 'Geyser Circuit' },
    { day: 3, date: '2026-07-03', title: 'Canyon & Wildlife' },
    { day: 4, date: '2026-07-04', title: 'Norris & Photography' }
  ],
  nodes: create([
    {
      id: 'flight-in',
      title: 'United Flight Richmond → Bozeman',
      category: 'flight',
      day: 1,
      timeWindow: '06:20–14:04',
      duration: '7h 44m',
      location: 'RIC → BZN',
      cost: 2520,
      priority: 'high',
      reservationStatus: 'booked',
      notes: '1 stop · family seats together',
      tags: ['arrival', 'air'],
      icon: '✈️',
      geo: { lat: 45.7772, lng: -111.152 },
      weights: { joy: 5, timeCost: 10, budgetImpact: 10, effort: 6, uniqueness: 2 }
    },
    {
      id: 'private-transfer',
      title: 'Private Transfer to Yellowstone',
      category: 'transport',
      day: 1,
      timeWindow: '14:30–16:00',
      duration: '1h 30m',
      location: 'Bozeman Airport → Yellowstone',
      cost: 438,
      priority: 'medium',
      reservationStatus: 'booked',
      notes: 'Luxury SUV with child seat',
      tags: ['ground transport'],
      icon: '🚘',
      geo: { lat: 44.976, lng: -110.702 },
      weights: { joy: 6, effort: 3, timeCost: 6 }
    },
    {
      id: 'mammoth',
      title: 'Mammoth',
      category: 'attraction',
      day: 1,
      timeWindow: '17:00–18:30',
      duration: '1h 30m',
      location: 'Mammoth Hot Springs',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Light walk on arrival day',
      tags: ['nature', 'family'],
      icon: '🏞️',
      geo: { lat: 44.976, lng: -110.702 },
      weights: { joy: 8, uniqueness: 8 }
    },
    {
      id: 'mammoth-dining',
      title: 'Mammoth Dining Room',
      category: 'restaurant',
      day: 1,
      timeWindow: '19:00–20:30',
      duration: '1h 30m',
      location: 'Mammoth Hotel',
      cost: 190,
      priority: 'high',
      reservationStatus: 'pending',
      notes: 'Window-side table requested',
      tags: ['dinner'],
      icon: '🍽️',
      geo: { lat: 44.9765, lng: -110.7005 },
      weights: { joy: 7, budgetImpact: 6, uniqueness: 5 }
    },
    {
      id: 'old-faithful',
      title: 'Old Faithful Geyser',
      category: 'attraction',
      day: 2,
      timeWindow: '08:00–09:00',
      duration: '1h',
      location: 'Old Faithful Area',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Catch morning eruption window',
      tags: ['must-see'],
      icon: '🌋',
      geo: { lat: 44.4605, lng: -110.8281 },
      weights: { joy: 9, uniqueness: 9 }
    },
    {
      id: 'grand-prismatic',
      title: 'Grand Prismatic Spring',
      category: 'scenic_point',
      day: 2,
      timeWindow: '09:30–11:00',
      duration: '1h 30m',
      location: 'Midway Geyser Basin',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Drone banned. Bring wide lens.',
      tags: ['photography'],
      icon: '🌈',
      geo: { lat: 44.525, lng: -110.8382 },
      weights: { joy: 10, uniqueness: 9, effort: 5 }
    },
    {
      id: 'castle-geyser',
      title: 'Castle Geyser',
      category: 'attraction',
      day: 2,
      timeWindow: '11:30–12:15',
      duration: '45m',
      location: 'Upper Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Flexible timing by eruption prediction',
      tags: ['geyser'],
      icon: '🗻',
      geo: { lat: 44.4629, lng: -110.8352 },
      weights: { joy: 7, uniqueness: 7 }
    },
    {
      id: 'fountain-paint-pot',
      title: 'Fountain Paint Pot',
      category: 'attraction',
      day: 2,
      timeWindow: '13:30–14:30',
      duration: '1h',
      location: 'Lower Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Boardwalk route stroller friendly',
      tags: ['family'],
      icon: '🎨',
      geo: { lat: 44.542, lng: -110.7939 },
      weights: { joy: 8, effort: 3 }
    },
    {
      id: 'west-thumb',
      title: 'West Thumb Geyser Basin',
      category: 'scenic_point',
      day: 2,
      timeWindow: '15:30–17:00',
      duration: '1h 30m',
      location: 'Yellowstone Lake',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Golden hour by the lake',
      tags: ['lake view'],
      icon: '🌊',
      geo: { lat: 44.4148, lng: -110.5728 },
      weights: { joy: 8, uniqueness: 8 }
    },
    {
      id: 'weather-decision',
      title: 'Weather Decision Gate',
      category: 'decision',
      day: 2,
      timeWindow: '17:00–17:15',
      duration: '15m',
      location: 'West Thumb parking',
      cost: 0,
      priority: 'low',
      reservationStatus: 'not_required',
      notes: 'If storms roll in, switch to fallback plan',
      tags: ['branching'],
      icon: '🔀',
      geo: { lat: 44.4151, lng: -110.5742 },
      weights: { joy: 5, effort: 2, uniqueness: 4 }
    },
    {
      id: 'indoor-fallback',
      title: 'Visitor Center + Relaxed Dinner',
      category: 'fallback',
      day: 2,
      timeWindow: '17:30–20:00',
      duration: '2h 30m',
      location: 'Old Faithful Visitor Education Center',
      cost: 120,
      priority: 'low',
      reservationStatus: 'not_required',
      notes: 'Backup for thunderstorms',
      tags: ['optional', 'weather-safe'],
      icon: '☔',
      optional: true,
      geo: { lat: 44.4605, lng: -110.8286 },
      weights: { joy: 6, budgetImpact: 5, effort: 2 }
    },
    {
      id: 'grand-canyon',
      title: 'Grand Canyon of Yellowstone',
      category: 'scenic_point',
      day: 3,
      timeWindow: '08:30–10:00',
      duration: '1h 30m',
      location: 'South Rim Drive',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Artist Point first',
      tags: ['iconic'],
      icon: '🏜️',
      geo: { lat: 44.7208, lng: -110.4963 },
      weights: { joy: 9, uniqueness: 8 }
    },
    {
      id: 'upper-falls',
      title: 'Yellowstone Upper Falls',
      category: 'scenic_point',
      day: 3,
      timeWindow: '10:15–11:00',
      duration: '45m',
      location: 'Brink of Upper Falls',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Short but steep walk',
      tags: ['waterfall'],
      icon: '💧',
      geo: { lat: 44.7148, lng: -110.5011 },
      weights: { joy: 8, effort: 6, uniqueness: 7 }
    },
    {
      id: 'hayden',
      title: 'Hayden Valley',
      category: 'scenic_point',
      day: 3,
      timeWindow: '14:00–15:30',
      duration: '1h 30m',
      location: 'Hayden Valley viewpoints',
      cost: 0,
      priority: 'high',
      reservationStatus: 'not_required',
      notes: 'Best for bison spotting',
      tags: ['wildlife'],
      icon: '🦬',
      geo: { lat: 44.6419, lng: -110.447 },
      weights: { joy: 9, uniqueness: 8 }
    },
    {
      id: 'wildlife-safari',
      title: 'Sunset Wildlife Safari',
      category: 'guided_activity',
      day: 3,
      timeWindow: '18:00–21:00',
      duration: '3h',
      location: 'Northern Range',
      cost: 560,
      priority: 'high',
      reservationStatus: 'pending',
      notes: 'Naturalist guide included',
      tags: ['guided', 'sunset'],
      icon: '🧭',
      geo: { lat: 45.026, lng: -110.704 },
      weights: { joy: 9, budgetImpact: 8, effort: 5, uniqueness: 8 }
    },
    {
      id: 'norris',
      title: 'Norris Geyser Basin',
      category: 'attraction',
      day: 4,
      timeWindow: '08:30–10:00',
      duration: '1h 30m',
      location: 'Norris',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Cooler morning recommended',
      tags: ['geyser basin'],
      icon: '♨️',
      geo: { lat: 44.7266, lng: -110.7045 },
      weights: { joy: 8, uniqueness: 8 }
    },
    {
      id: 'black-sand',
      title: 'Black Sand Basin',
      category: 'scenic_point',
      day: 4,
      timeWindow: '10:45–11:45',
      duration: '1h',
      location: 'Upper Geyser Basin',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Short colorful loop',
      tags: ['thermal'],
      icon: '🖤',
      geo: { lat: 44.4697, lng: -110.8304 },
      weights: { joy: 8, uniqueness: 7 }
    },
    {
      id: 'lake-butte',
      title: 'Lake Butte Overlook',
      category: 'scenic_point',
      day: 4,
      timeWindow: '13:00–14:00',
      duration: '1h',
      location: 'East of Yellowstone Lake',
      cost: 0,
      priority: 'medium',
      reservationStatus: 'not_required',
      notes: 'Best with clear skies',
      tags: ['overlook'],
      icon: '📸',
      geo: { lat: 44.5052, lng: -110.172 },
      weights: { joy: 8, uniqueness: 8 }
    },
    {
      id: 'photo-tour',
      title: 'Photography Tour',
      category: 'guided_activity',
      day: 4,
      timeWindow: '15:00–17:30',
      duration: '2h 30m',
      location: 'Yellowstone Lake area',
      cost: 480,
      priority: 'medium',
      reservationStatus: 'booked',
      notes: 'Private guide + premium lenses',
      tags: ['guided', 'photo'],
      icon: '📷',
      geo: { lat: 44.4212, lng: -110.3738 },
      weights: { joy: 9, budgetImpact: 7, uniqueness: 8 }
    },
    {
      id: 'slippery-otter',
      title: 'Slippery Otter Pub',
      category: 'restaurant',
      day: 4,
      timeWindow: '19:00–20:30',
      duration: '1h 30m',
      location: 'West Yellowstone',
      cost: 170,
      priority: 'high',
      reservationStatus: 'required',
      notes: 'Reserve patio if weather permits',
      tags: ['dinner', 'local favorite'],
      icon: '🍺',
      geo: { lat: 44.6624, lng: -111.1048 },
      weights: { joy: 7, budgetImpact: 6 }
    },
    {
      id: 'flight-out',
      title: 'Bozeman → Richmond Return Flight',
      category: 'flight',
      day: 4,
      timeWindow: '21:45–04:24+1',
      duration: '6h 39m',
      location: 'BZN → RIC',
      cost: 0,
      priority: 'high',
      reservationStatus: 'booked',
      notes: 'Red-eye return',
      tags: ['return'],
      icon: '🛫',
      geo: { lat: 45.7772, lng: -111.152 },
      weights: { joy: 4, timeCost: 9, effort: 6, uniqueness: 2 }
    }
  ]),
  edges: [
    { id: 'e1', source: 'flight-in', target: 'private-transfer', critical: true },
    { id: 'e2', source: 'private-transfer', target: 'mammoth', critical: true },
    { id: 'e3', source: 'mammoth', target: 'mammoth-dining', critical: true },
    { id: 'e4', source: 'mammoth-dining', target: 'old-faithful', critical: true },
    { id: 'e5', source: 'old-faithful', target: 'grand-prismatic', critical: true },
    { id: 'e6', source: 'grand-prismatic', target: 'castle-geyser', critical: true },
    { id: 'e7', source: 'castle-geyser', target: 'fountain-paint-pot', critical: true },
    { id: 'e8', source: 'fountain-paint-pot', target: 'west-thumb', critical: true },
    { id: 'e9', source: 'west-thumb', target: 'weather-decision', critical: true },
    { id: 'e10', source: 'weather-decision', target: 'grand-canyon', label: 'clear skies', critical: true },
    { id: 'e11', source: 'weather-decision', target: 'indoor-fallback', label: 'storm route' },
    { id: 'e12', source: 'indoor-fallback', target: 'grand-canyon', label: 'next morning' },
    { id: 'e13', source: 'grand-canyon', target: 'upper-falls', critical: true },
    { id: 'e14', source: 'upper-falls', target: 'hayden', critical: true },
    { id: 'e15', source: 'hayden', target: 'wildlife-safari', critical: true },
    { id: 'e16', source: 'wildlife-safari', target: 'norris', critical: true },
    { id: 'e17', source: 'norris', target: 'black-sand', critical: true },
    { id: 'e18', source: 'black-sand', target: 'lake-butte', critical: true },
    { id: 'e19', source: 'lake-butte', target: 'photo-tour', critical: true },
    { id: 'e20', source: 'photo-tour', target: 'slippery-otter', critical: true },
    { id: 'e21', source: 'slippery-otter', target: 'flight-out', critical: true }
  ]
};

export function createQuickNode(type: TripNodeType, id: string): TripNodeData {
  return node({
    id,
    title: `${type.replace('_', ' ')} node`,
    category: type,
    day: 1,
    timeWindow: '09:00–10:00',
    duration: '1h',
    location: 'Custom location',
    cost: 0,
    priority: 'medium',
    reservationStatus: 'not_required',
    notes: '',
    tags: ['new'],
    icon: '📍',
    geo: { lat: 44.6, lng: -110.6 },
    weights: { joy: 7, uniqueness: 5, effort: 4, timeCost: 4, budgetImpact: 4 }
  });
}
